# General Settings
name: Down Payment Project
job_title: Follow along as we build downpayment.gift
email: hello@downpayment.gift
description: Increasing access to homeownership for first-time buyers
avatar: /assets/images/dpg_profile.png
favicon: /favicon.ico
twitter_handler: your_handler
analytics_code: UA-100432438-15
#disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: 'https://facebook.com/downpaymentproject' }
-  { name: twitter, url: 'https://twitter.com/lorenwinzeler' }
-  { name: instagram, url: 'https://instagram.com/lorenwinzeler' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: 'https://www.youtube.com/channel/UCeUDMZ6NycRNHuXCjBvoKRA' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://downpaymentproject.com"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

